# Generated by Django 4.1.7 on 2023-05-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pdescr', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('pimg', models.ImageField(default='null.jpg', upload_to='productimg')),
            ],
        ),
    ]
