# Generated by Django 4.1.7 on 2023-05-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='pcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
