# Generated by Django 4.1.7 on 2023-05-29 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_productdb_pcategory'),
        ('UserModule', '0002_userdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='adminpanel.categorydb')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='adminpanel.productdb')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='UserModule.userdb')),
            ],
        ),
    ]
