# Generated by Django 4.1.7 on 2023-05-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0005_cartdb_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='shippingaddressdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=250)),
            ],
        ),
    ]
